### ISSUE TITLE
Some confusion about data

### ISSUE THREAD

**Issue by broalantaps** [llm-misinformation/llm-misinformation#2]
Hi Canyu,
How thrilling your work is! Your efforts have raised the bar for detecting fake news. I have a question about the CSV data: could you clarify the meaning of the "label" coulumn? My understanding is that all the data was generated by LLM, and the "label" column represents the output of your program. Am I correct? Thanks!

**Comment by canyuchen** [comment]
Thanks for the interest! "label = 1" represents "it is one piece of misinformation" "label = 0" represents "it is not one piece of misinformation"
